[package]
name = "viper"
version = "0.1.0"
authors = ["tkow <t.kusama0613@outlook.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
